version: "3"

services:
    back:
        ports:
            - "5000:5000"
        build:
            context: backend
            dockerfile: Dockerfile
    web:
        ports:
            - "4200:4200"
        build:
            context: frontend
            dockerfile: Dockerfile